{% set name = "wordllama" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dleemiller/WordLlama/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8afd5d41ece3c401486fb5cc2b7fd952e5886744555a76d7257dce52537ef38d

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - cython
    - numpy
  run:
    - python
    - numpy
    - safetensors
    - tokenizers
    - toml
    - pydantic >=2
    - requests

test:
  imports:
    - wordllama
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dleemiller/WordLlama
  summary: Fast, lightweight NLP toolkit designed for tasks like fuzzy deduplication, similarity computation, ranking, clustering, and semantic text splitting.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
